# This example configuration outlines how to configure the srsRAN Project gNB to create a single TDD cell
# transmitting in band 78, with 20 MHz bandwidth and 30 kHz sub-carrier-spacing. A USRP B200 is configured 
# as the RF frontend using split 8. Note in this example an external clock source is not used, so the sync 
# is not defined and the default is used. 

cu_cp:
  inactivity_timer: 7200
  amf:
    addr: ${AMF_ADDR}               # The address or hostname of the AMF.
    bind_addr: ${AMF_BIND_ADDR}         # A local IP that the gNB binds to for traffic from the AMF.
    supported_tracking_areas:                                    # Configure the TA associated with the CU-CP
      - tac: 1
        plmn_list:
          -
            plmn: "99970"
            tai_slice_support_list:
              -
                sst: 1
                sd: 0x111111
              
  f1ap:
    bind_addr: ${AMF_BIND_ADDR}    

# cu_up: 
#   f1u:
#       socket:
#         -
#           bind_addr: ${SRSRAN-CU-GTPU}

log:
  filename: stdout          # Path of the log file.
  all_level: info                   # Logging level applied to all layers.

pcap:
  ngap_enable: false                # Set to true to enable NGAP PCAPs.
  ngap_filename: ./gnb_ngap.pcap # Path where the NGAP PCAP is stored.
