# This example configuration outlines how to configure the srsRAN Project gNB to create a single TDD cell
# transmitting in band 78, with 20 MHz bandwidth and 30 kHz sub-carrier-spacing. A USRP B200 is configured 
# as the RF frontend using split 8. Note in this example an external clock source is not used, so the sync 
# is not defined and the default is used. 

cu_cp:
  amf:
    addr: ${AMF_ADDR}               # The address or hostname of the AMF.
    bind_addr: ${SRSRAN-CU-GTPU}           # A local IP that the gNB binds to for traffic from the AMF.
    supported_tracking_areas:            # Configure the TA associated with the CU-CP
      - tac: {{ .Values.config.cell_cfg.tac }}
        plmn_list:
          - plmn: "{{ .Values.config.cell_cfg.plmn }}"
            tai_slice_support_list:
                  {{- range .Values.config.slicing }}
                    - {{- toYaml . | nindent 6 }}
                    {{- end }}
  f1ap:
    bind_addr: ${SRSRAN-CU-F1AP}          

slicing:
  {{- range .Values.config.slicing }}
    - {{- toYaml . | nindent 6 }}
    {{- end }}

log:
  filename: stdout          # Path of the log file.
  all_level: info                   # Logging level applied to all layers.

pcap:
  mac_enable: false                 # Set to true to enable MAC-layer PCAPs.
  mac_filename: ./gnb_mac.pcap   # Path where the MAC PCAP is stored.
  ngap_enable: false                # Set to true to enable NGAP PCAPs.
  ngap_filename: ./gnb_ngap.pcap # Path where the NGAP PCAP is stored.
