# This example configuration outlines how to configure the srsRAN Project gNB to create a single TDD cell
# transmitting in band 78, with 20 MHz bandwidth and 30 kHz sub-carrier-spacing. A USRP B200 is configured 
# as the RF frontend using split 8. Note in this example an external clock source is not used, so the sync 
# is not defined and the default is used. 

f1ap:
  cu_cp_addr: ${CU_ADDR}
  bind_addr: ${DU_BIND_ADDR}
  
# f1u:
#   socket:
#     -
#       bind_addr: ${CU_ADDR}

ru_sdr:
  device_driver: {{ .Values.config.ru_sdr.device_driver }}                                               # The RF driver name.
  device_args: {{ .Values.config.ru_sdr.device_args }}     # Optionally pass arguments to the selected RF driver.
  srate: {{ .Values.config.ru_sdr.srate }}
  tx_gain: {{ .Values.config.ru_sdr.tx_gain }}                     # Transmit gain of the RF might need to adjusted to the given situation.
  rx_gain: {{ .Values.config.ru_sdr.rx_gain }}                       # Receive gain of the RF might need to adjusted to the given situation.

cell_cfg:
  dl_arfcn: {{ .Values.config.cell_cfg.dl_arfcn }}                  # ARFCN of the downlink carrier (center frequency).
  band: {{ .Values.config.cell_cfg.band }}                           # The NR band.
  channel_bandwidth_MHz: {{ .Values.config.cell_cfg.channel_bandwidth_MHz }}          # Bandwith in MHz. Number of PRBs will be automatically derived.
  common_scs: {{ .Values.config.cell_cfg.common_scs }}                    # Subcarrier spacing in kHz used for data.
  plmn: {{ .Values.config.cell_cfg.plmn }}                   # PLMN broadcasted by the gNB.
  tac: {{ .Values.config.cell_cfg.tac }}                            # Tracking area code (needs to match the core configuration).
  pdcch:
    common:
      ss0_index: 0                  # Set search space zero index to match srsUE capabilities
      coreset0_index: 12            # Set search CORESET Zero index to match srsUE capabilities
    dedicated:
      ss2_type: common              # Search Space type, has to be set to common
      dci_format_0_1_and_1_1: false # Set correct DCI format (fallback)
  prach:
    prach_config_index: 1           # Sets PRACH config to match what is expected by srsUE      
  pdsch:
    mcs_table: qam64                # Sets PDSCH MCS to 64 QAM
  pusch:
    mcs_table: qam64                # Sets PUSCH MCS to 64 QAM
  
  slicing:
  {{- range .Values.config.slicing }}
    - {{- toYaml . | nindent 6 }}
    {{- end }}


log:
  filename: stdout          # Path of the log file.
  all_level: info                   # Logging level applied to all layers.

pcap:
  mac_enable: false                 # Set to true to enable MAC-layer PCAPs.
  mac_filename: ./gnb_mac.pcap   # Path where the MAC PCAP is stored.

metrics:
    enable_json_metrics: true       # Enable reporting metrics in JSON format
    addr: ${METRICS_ADDR}                # Metrics-server IP
    port: 55555                     # Metrics-server Port

