apiVersion: v1
kind: Service
metadata:
  name: srsran-ue
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: rx
      port: 2000
      targetPort: 2000
      protocol: TCP
    - name: tx
      port: 2001
      targetPort: 2001
      protocol: TCP
  selector:
    app.kubernetes.io/name: srsran-ue
