apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: grafana-route
spec:
  host: srsran-grafana.sno.oran.lab
  port:
    targetPort: http  # This must match the port name in your Grafana service
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Allow
  to:
    kind: Service
    name: metrics-server
    weight: 100
  wildcardPolicy: None
