apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: grafana-route  # Or any unique name in the namespace
spec:
  host: grafana-srsran.sno.oran.lab
  port:
    targetPort: http  # Must match the port NAME in Grafana service
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Allow
  to:
    kind: Service
    name: grafana-service  # Must match the name of your Grafana service!
    weight: 100
  wildcardPolicy: None
