apiVersion: v1
kind: Service
metadata:
  name: grafana-service # Renamed for clarity
  labels: #Ensure that labels are linked to the grafana pods instead of srsran pods
    app: grafana-srsran #Example only, please change according to your configuration
spec:
  selector:
    app: grafana-srsran # Select the correct Grafana pods
  ports:
    - port: 3000          # The port exposed by the service
      targetPort: 3000  # The actual port inside the container
      protocol: TCP
      name: http
  type: ClusterIP # Ensure a ClusterIP service is requested
